# Generated by Django 5.1.7 on 2025-03-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0015_alter_workorder_work_trenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='process_pattern',
            field=models.CharField(choices=[('1', 'No.1'), ('2', 'No.2'), ('3', 'No.3'), ('4', 'No.4'), ('5', '一般工程'), ('6', 'その他')], max_length=10, verbose_name='製造工程パタン'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_range',
            field=models.CharField(default='ページ', max_length=200, verbose_name='作業範囲'),
        ),
    ]
