# Generated by Django 5.1.7 on 2025-03-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0016_alter_workorder_process_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_type',
            field=models.CharField(choices=[('1', 'FB'), ('2', 'PL')], max_length=2, verbose_name='FB・PL'),
        ),
    ]
