# Generated by Django 5.1.7 on 2025-03-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0017_alter_workorder_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='planed_value',
            field=models.DecimalField(decimal_places=0, default='', max_digits=3, verbose_name='計画数'),
        ),
    ]
