# Generated by Django 5.1.7 on 2025-04-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0014_alter_workorder_planed_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='buy_check',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='購買確認'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='publish_check',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='作成'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='recive_check',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='受け取り確認'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='syounin_check',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='承認'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workset_check',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='工数設定'),
        ),
    ]
